### PR TITLE
Terraform + Dockerfile

### PR DESCRIPTION
**Pull request by Stringls**
https://github.com/Stringls/Chess

Hello, here it is. I've added to my project Dockerfile and created Terraform.
Also I've changed a bit the workflow, fixed the transient failure of database when running the web app on Azure as I mentioned in the last issue.

I will be glad if you indicate problems in my code, if any.
Thank you)

### CODE REVIEW

**Comment by Stringls** [comment]
All the problems I noticed have been fixed. I also have a suggestion to create a README.md file in the "terraform" folder, it will be useful IMHO.

**Comment by psp87** [comment]
Hi, unfortunately, I still see lot of changes in the PR. Did you push after merging master? Maybe you can pull the main branch and create a new branch. Then only your changes will appear in the PR and it will be much easier to see them.

**Comment by Stringls** [comment]
Hello, I created an other branch that is called "master", this branch is up to date and there are no conflicts. I hope you are gonna be able to see my commits.

**Comment by psp87** [comment]
Again, I see 96 commits to be added. There is an old branch new-db-tables that is many commits behind the master. It seems you are pushing these changes that are out of date ([Stringls](https://github.com/Stringls) wants to merge 96 commits into [master](https://github.com/psp87/Chess) from [new-db-tables](https://github.com/psp87/Chess/tree/new-db-tables)). I will delete this branch (PR will also be deleted). Please pull again the master branch and create a new PR with new commits.

**Pull request closed without merging**
